site_name: Guide | Summer 2021 of Open Source Promotion Plan
site_dir: public

theme:
  name: material
  language: 'en'
  features:
    - navigation.expand

plugins:
    - search

nav:
  - Frequently Asked: index.md
  - Roles: roles.md
  - Timeline: timeline.md
  - Student Guide:
    - Questions: student.md
    - Suggestions: proj_apply.md
  - Community: community.md
  - Mentor: mentor.md
  - Cooperation: cooperation.md
  - Contact Us: contactus.md
  - Acknowledgements: acknowledgements.md
